import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MsalProviderWrapper from "./MsalProviderWrapper"; // Import the MSAL wrapper

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Check User - Supplier Link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap the children with MsalProviderWrapper */}
        <MsalProviderWrapper>
          {children}
        </MsalProviderWrapper>
      </body>
    </html>
  );
}
